name: MafiaChat
main: Mohi\MafiaChat\MafiaChat
author: "물외한인(Mohi)"
version: "1.0.1"
api:
- 1.13.0
- 2.0.0

permissions:
 free.broadcast.allow:
  descript: "allow free broadcast message"
  default: OP