name: MohiPia
main: Mohi\MohiPia\MohiPia
author: "Mohi(물외한인)"
version: "1.0.1"
api:
- 1.13.0
- 2.0.0

permissions:
 make.room.command:
  descript: "make a new room"
  default: true
 stop.mafia.game.command:
  descript: "stop the mafia game"
  default: OP
 delete.room.command:
  descript: "delete the room"
  default: OP